config/routes.rb
Rails.application.routes.draw do
  devise_for :accounts, :controllers => {:registrations => "registrations"}

  root 'welcome#index'
  resources :readings do
    collection do
      get 'reports_daily', as: "daily"
      get 'reports_month_date', as: "month_date"
      get 'reports_monthly', as: "monthly"
    end
  end

  get "/check_reading_limit", controller: 'readings', action: "check_reading_limit"













  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/controllers/readings_controller.rb
class ReadingsController < ApplicationController
	def index
		render :reports
	end

	def new
		@reading = GlucoseReading.new
	end

	def create
		d = Date.strptime(reading_params["date"], '%d-%m-%Y')
		
		if reading_params[:time].present?
			t = DateTime.parse reading_params["time"]
			@dt = DateTime.new(d.year, d.month, d.day, t.hour, t.min)
		end

		@reading_obj = GlucoseReading.new(recorded_date: @dt, description: reading_params["description"],amount: reading_params["amount"])
		@reading_obj.patient_id = current_account.accountable_id
		
		if @reading_obj.save
			flash.now[:success] = "Saved"
			render "new"
		else
			flash.now[:error] = @reading_obj.errors.full_messages
			render "new"
		end
	end

	def check_reading_limit
    count = GlucoseReading.where("str_to_date(recorded_date,'%Y-%m-%d')=?", reading_params["date"]).count
  	respond_to do |format|
  	  format.json {render json: count < CheckValidation::PER_DAY_ENTRY_LIMIT}
  	end
	end

	# gives report for specified date
	def reports_daily
		if params.has_key?("date")
			date = Time.parse(params["date"]).strftime("%Y-%m-%d")
		else
			date = Date.today.strftime('%Y-%m-%d')
		end

		@readings = current_account.accountable.glucose_readings.daily_report(date)
		@max = @readings.maximum("amount")
		@avg = @readings.average("amount").to_f
		@readings = @readings.paginate(:page => params[:page], per_page: 5)
		respond_to do |format|
			format.html { render "reports"}
			format.js { render "reports"}
		end	
	end

	# for date 15/7/16, gives report from 1/7/16 --> 15/7/16 (inclusive)
	def reports_month_date
		if params.has_key?("date")
			date = Time.parse(params["date"]).strftime("%Y-%m-%d")
		else
			date = Date.today.strftime('%Y-%m-%d')
		end
		@readings = current_account.accountable.glucose_readings.monthdate_report(date)
		@max = @readings.maximum("amount")
		@avg = @readings.average("amount").to_f
		@readings = @readings.paginate(page: params[:page], per_page: 5)
		respond_to do |format|
			format.html { render "reports"}
			format.js { render "reports"}
		end	
	end

	# for date 1/7/16, gives report from 2/6/16 --> 1/7/16 (inclusive)
	def reports_monthly
		if params.has_key?("date")
			date = Time.parse(params["date"]).strftime("%Y-%m-%d")
		else
			date = Date.today.strftime('%Y-%m-%d')
		end
		@readings = current_account.accountable.glucose_readings.monthly_report(date)
		@max = @readings.maximum("amount")
		@avg = @readings.average("amount").to_f
		@readings = @readings.paginate(page: params[:page], per_page: 5)
		respond_to do |format|
			format.html { render "reports"}
			format.js { render "reports"}
		end	
	end

	private 
	def reading_params
		params.require(:reading).permit(:date, :time, :description, :amount)
	end
end

app/helpers/readings_helper.rb
module ReadingsHelper
end

app/views/readings/_report.html.erb
  
  <% if request.format == "text/javascript" %>
  <% @max ||= max 
      @readings ||= readings
      @avg ||= avg
  %>
  <% end %>


  <div class="col-lg-2 col-lg-offset-1">
    <div class="panel panel-primary media-body">
        <div class="panel-body blue">
          <i class="fa fa-heartbeat fa-3x"></i>
          <h3><%= @max %> </h3>
        </div>
        <div class="panel-footer">
          <span class="panel-eyecandy-title">Highest Glycemic Index
          </span>
        </div>
    </div>

    <div class="panel panel-primary media-body">
      <div class="panel-body green">
        <i class="fa fa-medkit fa-3x"></i>
        <h3><%= @avg %> </h3>
      </div>
      <div class="panel-footer">
        <span class="panel-eyecandy-title">Average Glycemic Index
        </span>
      </div>
    </div>
 </div>

  <div class="col-lg-5 col-lg-offset-2">
    <table id="results-table" class="table table-bordered table-hover">
      <thead>
        <th>Patient Name</th>
        <th>Recorded Date</th>
        <th>Glycemic Index</th>
        <th>Description</th>
      </thead>
      <tbody>
        <% if !@readings.nil? %>
          <% for data in @readings %>
            <tr>
              <td><%= data.patient.name %></td>
              <td><%= data.recorded_date %></td>
              <td><%= data.amount %></td>
              <td><%= data.description %></td>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
    <%= will_paginate @readings %>
  </div>

app/views/readings/new.html.erb
<% @dt ||= @dt %>
<div id="page-wrapper">
<div class="row">
	<h1 class="page-header">Enter Reading</h1>
 	<% if flash[:error] %>
		<div class="alert alert-danger"> 
      <%= flash[:error] %>
    </div>
  <% end %>
	<% if flash[:success] %>
    <div class="alert alert-success">  
      <%= flash[:success] %>
    </div>
  <% end %>

		<%= form_tag('/readings', method: :post, id: 'new_form') do %>
		<% fields_for :reading do |f| %>
		<div class="row">
			<div class="col-lg-2 form-group">
				<span><b>Date:</b></span>
				<div id="datepicker" class=" input-prepend date">
					
		  		<span class="add-on"><i class="fa fa-calendar"></i></span>
		  		<input class="span2" name="reading[date]" type="text" value=<%= Date.today.strftime('%d-%m-%Y')%>>
				</div>
			</div>
			
			<div class="col-lg-2">
				<span><b>Time</b> </span>
				<div class="input-prepend bootstrap-timepicker timepicker">
	    		
	    		<span class="add-on"><i class="fa fa-clock-o"></i></span>
	    		<input id="timepicker1" name="reading[time]" type="text" class="span2">
				</div>
			</div>
		</div>
		<div class="col-lg-4">
		<div class="form-group">
			<%=f.label :description %>
			<%=f.text_area :description, class: "form-control" %>
		</div>
		<div class="form-group">
			<%=f.label :amount, 'Glycemic value' %>
			<%=f.text_field :amount, class: "form-control" %>
		</div>

		<%=f.submit "Save", class: "btn btn-lg btn-success"%>
		</div>
		<% end %>
		<% end %>
	</div>
</div>

app/views/readings/reports.html.erb
<style>
.nav-tabs{
  background-color:#41b1c9;
}

.nav-tabs > li > a {
	color: #ffffff;
}
.nav-tabs > li > a.active,
nav-tabs > li > a:hover,
.nav-tabs > li.active > a:focus {
          color: #555555;
          cursor: default;
          background-color: #ffffff;
          border: 4px solid #1ea76d;
          border-bottom-color: transparent;
          } 
</style>

<div id="page-wrapper">
	<div class="row">
		<h1 class="page-header">Reports</h1>
		<!-- <div class="container"> -->
		<div class="row">
			<div class="col-lg-5">
				<ul class="nav nav-tabs">
					<li><%=link_to "Daily Report", daily_readings_path, class: "active", id: "d-tab" %></li>
					<li><%=link_to "Month to Date Report", month_date_readings_path, id: "md-tab" %></li>
					<li><%=link_to "Monthly Report", monthly_readings_path(), id: "m-tab" %></li>
				</ul>
			</div>	
			<div class="col-lg-3">
				Pick Date: <div id="datepicker2" class=" input-prepend date">
		  		<span class="add-on"><i class="fa fa-calendar"></i></span>
		  		<input class="span2" type="text" id="date-daily" value=<%= Date.today.strftime('%d-%m-%Y') %>>
				</div>
 			</div>
 		</div>
 		<div class="row tab-content" id="report_tab">
 		 <%= render "report" %>
 	</div>
</div>

<script>
$(function(){
 $("#md-tab, #d-tab, #m-tab").click(function(evt){
	evt.preventDefault();
	var url = $('.nav-tabs .active').attr('href');
    var dateText = $('#date-daily').val();
	$.ajax({
    	type:'GET',
    	dataType: "script",
    	url: url,
    	data: {date: dateText}
  	});
  });      
});
</script>

app/views/readings/reports.js.erb
$('#report_tab').html("<%= j (render :partial => 'readings/report', locals: {readings: @readings, max: @max, avg: @avg}) %>");