config/routes.rb
Rails.application.routes.draw do
  devise_for :accounts, :controllers => {:registrations => "registrations"}

  root 'welcome#index'
  resources :readings do
    collection do
      get 'reports_daily', as: "daily"
      get 'reports_month_date', as: "month_date"
      get 'reports_monthly', as: "monthly"
    end
  end

  get "/check_reading_limit", controller: 'readings', action: "check_reading_limit"













  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sweety App</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.3.0/css/font-awesome.css">
  <%= csrf_meta_tags %>

</head>
<body>
  <% if account_signed_in? %>
  <div id="wrapper">
  <div id="navbar" class="navbar navbar-default navbar-fixed-top">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#collapsibleMenu">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a href="#" style="color:white;font-weight:bold;font-size:20px;margin-top:30px">Sweety App</a>
    </div>
    <div class="collapse navbar-collapse" id="collapsibleMenu">
      <ul class="navbar-top-links navbar-nav nav navbar-right">
        <li>
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">
          <i class="fa fa-user fa-3x"></i>
        </a>
        <ul class="dropdown-menu dropdown-user">
          <li><%= link_to "Logout", destroy_account_session_path, method: :delete, class: "navbar-link" %></li>
        </ul>
         </li>
      </ul>
    </div>
  </div>

    <!-- Sidebar -->

    <nav class="navbar-default navbar-static-side" role="navigation">
      <div class="sidebar-collapse">
        <ul id="side-menu" class="nav">
        <li>
          <div class="user-section">
            <div class="user-section-inner">
                <img src="/assets/user.jpg" alt="">
            </div>
            <div class="user-info">
                <div><%= current_account.email%></div>
                <div class="user-text-online">
                    <span class="user-circle-online btn btn-success btn-circle "></span>&nbsp;Online
                </div>
            </div>
        
          </div>
        </li>

        <li class="selected">
          <a href=<%= root_url %>><i class="fa fa-dashboard fa-fw"></i>Dashboard</a>
          <a href=<%= daily_readings_url %>><i class="fa fa-rss-square fa-fw"></i>Reports</a>
        </li>
      </ul>
      </div>
    </nav>
    
    <%= yield %>
 </div>
 <% else %>
   <%= yield %>
  <% end %>
</body>
</html>